// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class FormaPagamento
    {
        public FormaPagamento()
        {
            Pagar = new HashSet<Pagar>();
        }

        public int IdFormaPagamento { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<Pagar> Pagar { get; set; }
    }
}