// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class Investimento
    {
        public Investimento()
        {
            Poupanca = new HashSet<Poupanca>();
            PrevidenciaPrivada = new HashSet<PrevidenciaPrivada>();
            RendaVariavel = new HashSet<RendaVariavel>();
        }

        public int IdInvestimento { get; set; }
        public string Descricao { get; set; }
        public string NomeTipoInvestimento { get; set; }
        public int IdCarteira { get; set; }

        public virtual Carteira IdCarteiraNavigation { get; set; }
        public virtual ICollection<Poupanca> Poupanca { get; set; }
        public virtual ICollection<PrevidenciaPrivada> PrevidenciaPrivada { get; set; }
        public virtual ICollection<RendaVariavel> RendaVariavel { get; set; }
    }
}