// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class Pagar
    {
        public int IdPagar { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public bool Pago { get; set; }
        public decimal Valor { get; set; }
        public string Categoria { get; set; }
        public int IdCarteira { get; set; }
        public int IdFormaPagamento { get; set; }

        public virtual Carteira IdCarteiraNavigation { get; set; }
        public virtual FormaPagamento IdFormaPagamentoNavigation { get; set; }
    }
}