// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class Poupanca
    {
        public int IdPoupanca { get; set; }
        public string Nome { get; set; }
        public int IdInvestimento { get; set; }

        public virtual Investimento IdInvestimentoNavigation { get; set; }
    }
}