// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class Receber
    {
        public int IdReceber { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
        public byte Recebido { get; set; }
        public DateTime Data { get; set; }
        public string Categoria { get; set; }
        public int IdCarteira { get; set; }

        //FAKE
        public int Id_sistema { get; set; }

        public virtual Carteira IdCarteiraNavigation { get; set; }
    }
}