// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TesteEFToolPower.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            Carteira = new HashSet<Carteira>();
            Relatorio = new HashSet<Relatorio>();
        }

        public int IdUsuario { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }

        public DateTime Data_nascimento { get; set; }

        public string Telefone { get; set; }

        public string Image { get; set; }

        //Data nascimento, 
        public virtual ICollection<Carteira> Carteira { get; set; }
        public virtual ICollection<Relatorio> Relatorio { get; set; }
        
    }
}