// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopularBancoFalso.Data;

namespace PopularBancoFalso.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PopularBancoFalso.Models.Registro", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria_pagar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAplicacao_rendavariavel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_pagar")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao_investimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao_pagar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCarteira")
                        .HasColumnType("int");

                    b.Property<int>("IdCarteira_investimento")
                        .HasColumnType("int");

                    b.Property<int>("IdCarteira_pagar")
                        .HasColumnType("int");

                    b.Property<int>("IdCarteira_receber")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPagamento")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPagamento_pagar")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestimento")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestimento_poupanca")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestimento_previdencia")
                        .HasColumnType("int");

                    b.Property<int>("IdInvestimento_rendavariavel")
                        .HasColumnType("int");

                    b.Property<int>("IdPagar")
                        .HasColumnType("int");

                    b.Property<int>("IdPoupanca")
                        .HasColumnType("int");

                    b.Property<int>("IdPrevidencia")
                        .HasColumnType("int");

                    b.Property<int>("IdReceber")
                        .HasColumnType("int");

                    b.Property<int>("IdRelatorio")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario_carteira")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario_relatorio")
                        .HasColumnType("int");

                    b.Property<int>("IdVariavel")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTipoInvestimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_carteira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_forma_pagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_poupanca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_previdencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<string>("Papel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Recebido")
                        .HasColumnType("tinyint");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRelatorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unidades")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_pagar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_previdencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
